#!/bin/bash

# 跳到当前目录
cd `dirname "$0"`

# 脚本所在目录
BASE_DIR=$(pwd)

# 移除 pid 文件、日志、Core 文件
echo "Start removing junk files."
find . -name *.pid | xargs rm -fv
find . -name *.log | xargs rm -fv
find . -name core.* | xargs rm -fv
echo "End junk file removal."
sleep 3

# echo "##### stun start #####"
cd ${BASE_DIR}/stun
chmod +x df_stun_r
./df_stun_r start &

# echo "##### monitor start #####"
cd ${BASE_DIR}/monitor
chmod +x df_monitor_r
./df_monitor_r mnt_cain start &

# echo "##### manager start #####"
cd ${BASE_DIR}/manager
chmod +x df_manager_r
./df_manager_r manager start &

# echo "##### relay start #####"
cd ${BASE_DIR}/relay
chmod +x df_relay_r
./df_relay_r relay_200 start &

# echo "##### bridge start #####"
cd ${BASE_DIR}/bridge
chmod +x df_bridge_r
./df_bridge_r bridge start &

# echo "##### channel start #####"
cd ${BASE_DIR}/channel
chmod +x df_channel_r
./df_channel_r channel start &

# echo "##### dbmw_guild start #####"
cd ${BASE_DIR}/dbmw_guild
chmod +x df_dbmw_r
./df_dbmw_r dbmw_gld_cain start &

# echo "##### dbmw_mnt start #####"
cd ${BASE_DIR}/dbmw_mnt
chmod +x df_dbmw_r
./df_dbmw_r dbmw_mnt_cain start &

# echo "##### dbmw_stat start #####"
cd ${BASE_DIR}/dbmw_stat
chmod +x df_dbmw_r
./df_dbmw_r dbmw_stat_cain start &

# echo "##### guild start #####"
cd ${BASE_DIR}/guild
chmod +x df_guild_r
./df_guild_r gld_cain start &

# echo "##### statics start #####"
cd ${BASE_DIR}/statics
chmod +x df_statics_r
./df_statics_r stat_cain start &

# echo "##### coserver start #####"
cd ${BASE_DIR}/coserver
chmod +x df_coserver_r
./df_coserver_r coserver start &

# echo "##### community start #####"
cd ${BASE_DIR}/community
chmod +x df_community_r
./df_community_r community start &

# echo "##### gunnersvr start #####"
cd ${BASE_DIR}/secsvr/gunnersvr
chmod +x gunnersvr
./gunnersvr -t30 -i1 &

# echo "##### zergsvr start #####"
cd ${BASE_DIR}/secsvr/zergsvr
chmod +x secagent
chmod +x zergsvr
./secagent &
./zergsvr -t30 -i1 &

cd ${BASE_DIR}/game
chmod +x df_game_r

# echo "##### game start #####"
sleep 5
./df_game_r cain01 start &

# echo "##### pvp start #####"
sleep 120
./df_game_r cain02 start &
